const express = require('express');
const path = require('path');
const fs = require('fs');
const app = express();

app.use(express.json());

const PathToFile = path.join(__dirname, 'items.json');

 // middleware check function..
const check = (req,res,next) => {
  const {itemName, type, place, date, contact} = req.body;

  if (!itemName || !type || !place || !date || !contact) {
    return res.status(400).json({ error: 'All fields are required '});
  }

  if (type !== 'lost' && type !== 'found') {
    return res.status(400).json({ error: 'Type must be lost or found'});
  }

  next();
}


// post request..
app.post('/api/items', check, (req,res) => {

  const {itemName, type, place, date, contact} = req.body;

  fs.readFile(PathToFile, 'utf-8', (err,data) => {

    if (err) {
      return res.status(500).json({ error: 'Failed to read items file' });
    }
    const items = JSON.parse(data);

    const itemToPush = {
      'id': String(Date.now()),
      'itemName': itemName,
      'type': type,
      'place': place,
      'date': date,
      'contact': contact,
      'status': 'open'
    }
    items.push(itemToPush);
    fs.writeFile(PathToFile, JSON.stringify(items), (err) => {
      if (err) {
        return res.status(500).json({ error: 'Failed to save item' });
      }

      return res.status(201).json(itemToPush);

    });

  });
});

// returns the whole array
app.get('/api/items', (req, res) => {
  fs.readFile(PathToFile, 'utf-8', (err, data) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to read items file' });
    }
    const items = JSON.parse(data);
    const { type, status, place } = req.query;

    let result = items;

    if (type) {
      result = result.filter(item => item.type === type);
    }
    if (status) {
      result = result.filter(item => item.status === status);
    }
    if (place) {
      result = result.filter(item => item.place.toLowerCase().includes(place.toLowerCase()));
    }

    // as the id is generated by Date.now(), so the newest item id will be larger in the timestamp.. hence we can sort...
    result.sort((a,b) => Number(b.id) - Number(a.id))

    return res.status(200).json(result);
  })
});

// return a particular item
app.get('/api/items/:id', (req,res) => {
  fs.readFile(PathToFile, 'utf-8', (err, data) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to read items file' });
    }

    const items = JSON.parse(data);

    const item = items.find(item => item.id === req.params.id);

    if (!item) {
      return res.status(404).json({ error: 'Not found' });
    }
    return res.status(200).json(item);
  });
});

// PUT request
app.put('/api/items/:id', check, (req,res) => {
  const { itemName, type, place, date, contact } = req.body;

  fs.readFile(PathToFile, 'utf-8', (err, data) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to read items file' });
    }
    
    const items = JSON.parse(data);

    const index = items.findIndex(item => item.id === req.params.id);

    if (index === -1) {
      return res.status(404).json({ error: 'Not found' });
    };

    items[index].itemName = itemName;
    items[index].type = type;
    items[index].place = place;
    items[index].date = date;
    items[index].contact = contact;

    fs.writeFile(PathToFile, JSON.stringify(items), (err) => {
      if (err) {
        return res.status(500).json({ error: 'Failed to save item' });
      }

      return res.status(200).json(items[index]);
    });
  });
});

//Patch request
app.patch('/api/items/:id/claim', (req, res) => {
  
  fs.readFile(PathToFile, 'utf-8', (err, data) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to read items file' });
    }

    const items = JSON.parse(data);

    const index = items.findIndex(item => item.id === req.params.id);

    if (index === -1) {
      return res.status(404).json({
        error: 'Not found' });
    }

    if (items[index].status === 'claimed') {
      return res.status(409).json({ error: 'Item is already claimed' });
    }

    items[index].status = 'claimed';
    
    fs.writeFile(PathToFile, JSON.stringify(items),(err) => {
      if (err) {
        return res.status(500).json({ error: 'Failed to save item' });
      }
      
      return res.status(200).json(items[index]);
    });
  });
});

// DELETE request

app.delete('/api/items/:id', (req, res) => {
  
  fs.readFile(PathToFile, 'utf-8', (err, data) => {
    if (err) {
      return res.status(500).json({ error: 'Failed to read items file' });
    }
    
    const items = JSON.parse(data);

    const index = items.findIndex(item => item.id === req.params.id);

    if (index === -1) {
      return res.status(404).json({ error: 'Not found' });
    }

    items.splice(index, 1);

    fs.writeFile(PathToFile, JSON.stringify(items), (err) => {
      if (err) {
        return res.status(500).json({ error: 'Failed to save items' });
      }
      
      return res.status(204).send();
    });
  });
});





app.listen(3000);
